apiVersion: v2

name: kube-janitor
description: Clean up (delete) Kubernetes resources after a configured TTL (time to live)

type: application

keywords:
    - ohio
    - application
    - custom

home: https://github.com/vptimmy/kube-janitor

maintainers:
  - name: Tim Hibbard
    email: vptimmy@gmail.com

version: 0.1.1
appVersion: "20.4.1"
